openapi: 3.0.0
info:
  title: Owlistic API
  version: 1.0.0
  description: API documentation for Owlistic application.
servers:
  - url: http://localhost:8080/api/v1
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input
        '401':
          description: Invalid email or password
        '500':
          description: Internal server error

  /tasks:
    get:
      summary: Get all tasks
      parameters:
        - name: user_id
          in: query
          required: false
          schema:
            type: string
        - name: completed
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal server error

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                user_id:
                  type: string
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /tasks/{id}:
    get:
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error

    put:
      summary: Update a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error

  /trash:
    get:
      summary: Get all trashed items
      responses:
        '200':
          description: A list of trashed items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrashedItem'
        '401':
          description: User not authenticated
        '500':
          description: Internal server error

    delete:
      summary: Empty trash
      responses:
        '200':
          description: Trash emptied successfully
        '500':
          description: Internal server error

  /trash/restore/{type}/{id}:
    post:
      summary: Restore a trashed item
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item restored successfully
        '400':
          description: Unsupported item type
        '500':
          description: Internal server error

  /trash/{type}/{id}:
    delete:
      summary: Permanently delete a trashed item
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item permanently deleted
        '400':
          description: Unsupported item type
        '500':
          description: Internal server error

  /notebooks:
    get:
      summary: Get all notebooks
      responses:
        '200':
          description: A list of notebooks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notebook'
        '500':
          description: Internal server error

    post:
      summary: Create a new notebook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                user_id:
                  type: string
      responses:
        '201':
          description: Notebook created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notebook'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /notebooks/{id}:
    get:
      summary: Get notebook by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Notebook found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notebook'
        '404':
          description: Notebook not found
        '500':
          description: Internal server error

    put:
      summary: Update a notebook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notebook'
      responses:
        '200':
          description: Notebook updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notebook'
        '404':
          description: Notebook not found
        '500':
          description: Internal server error

    delete:
      summary: Delete a notebook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Notebook deleted successfully
        '404':
          description: Notebook not found
        '500':
          description: Internal server error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        user_id:
          type: string
          format: uuid
        is_completed:
          type: boolean

    TrashedItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        type:
          type: string

    Notebook:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        user_id:
          type: string
          format: uuid