import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import openapiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  apiSidebar: { API: openapiSidebar },
};

export default sidebars;
