openapi: 3.0.0
info:
  title: OWListic API
  description: API documentation for OWListic application
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input
        '401':
          description: Invalid email or password
        '500':
          description: Internal server error

  /tasks:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                user_id:
                  type: string
                note_id:
                  type: string
              required:
                - title
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
    put:
      summary: Update a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
        '500':
          description: Internal server error
    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task deleted successfully
        '404':
          description: Task not found
        '500':
          description: Internal server error

  /trash:
    get:
      summary: Get all trashed items
      responses:
        '200':
          description: A list of trashed items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TrashedItem'
    delete:
      summary: Empty trash
      responses:
        '200':
          description: Trash emptied successfully
        '500':
          description: Internal server error

  /trash/restore/{type}/{id}:
    post:
      summary: Restore a trashed item
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item restored successfully
        '400':
          description: Invalid input
        '404':
          description: Item not found
        '500':
          description: Internal server error

  /trash/{type}/{id}:
    delete:
      summary: Permanently delete a trashed item
      parameters:
        - name: type
          in: path
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item permanently deleted
        '400':
          description: Invalid input
        '404':
          description: Item not found
        '500':
          description: Internal server error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        user_id:
          type: string
        note_id:
          type: string
        is_completed:
          type: boolean
    TrashedItem:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        type:
          type: string